use MD5 from openssl if available
git-svn-id: http://svn.berlios.de/svnroot/repos/sipsak/trunk@198 75b5f7c7-cfd4-0310-b54c-e118b2c5249a

diff --git a/sipsak/configure b/sipsak/configure
--- a/sipsak/configure
+++ b/sipsak/configure
@@ -4357,7 +4357,8 @@ done
 
 
 
-for ac_header in arpa/inet.h getopt.h netdb.h netinet/in.h netinet/in_systm.h stdlib.h string.h sys/socket.h sys/time.h unistd.h
+
+for ac_header in arpa/inet.h getopt.h netdb.h netinet/in.h netinet/in_systm.h openssl/md5.h stdlib.h string.h sys/socket.h sys/time.h unistd.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -5364,6 +5365,76 @@ _ACEOF
 
 fi
 done
+
+
+echo "$as_me:$LINENO: checking for MD5_Init in -lcrypto" >&5
+echo $ECHO_N "checking for MD5_Init in -lcrypto... $ECHO_C" >&6
+if test "${ac_cv_lib_crypto_MD5_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcrypto  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char MD5_Init ();
+int
+main ()
+{
+MD5_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_crypto_MD5_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_crypto_MD5_Init=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_crypto_MD5_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_crypto_MD5_Init" >&6
+if test $ac_cv_lib_crypto_MD5_Init = yes; then
+  LIBS="$LIBS -lcrypto"
+
+fi
 
 
 
